### PR TITLE
fix: display deadline date on new extension usage

### LINKED ISSUE #84: Write Deadline Extension New Date
We should state the new deadline for clarity. 

Try something like:

@user, you have used <code>**3**</code> of <code>**3**</code> available deadline extensions. Please provide an update on your progress. The new deadline is on 6 March 16:08 UTC.

> @user, you have used <code>**3**</code> of <code>**3**</code> available deadline extensions. Please provide an update on your progress.

_Originally posted by @ubiquity-os-beta[bot] in https://github.com/ubiquity-os-marketplace/command-ask/issues/70#issuecomment-2693229538_

### PR DESCRIPTION
**Pull request by gentlementlegen**
Resolves #84

QA: https://github.com/Meniole/daemon-disqualifier/issues/34#issuecomment-2709542900

### CODE REVIEW

File: src/helpers/remind-and-remove.ts [hunk 1]
```diff
@@ -97,39 +99,54 @@ async function shouldDisplayRemainingExtensionsReminder(context: ContextPlugin,
...
+  const currentExtensionsMilestone = args.extensions.extensionsLimit - args.remainingExtensions + 1;
+  const reminderContent = !shouldDisplayExtensions
     ? "this task has been idle for a while"
-    : `you have used <code>**${args.extensionsLimit - args.remainingExtensions + 1}**</code> of <code>**${args.extensionsLimit}**</code> available deadline extensions`;
+    : `you have used <code>**${currentExtensionsMilestone}**</code> of <code>**${args.extensions.extensionsLimit}**</code> available deadline extensions`;
+  const message = [`@${logins}, ${reminderContent}.`, "Please provide an update on your progress."];
+
+  if (shouldDisplayExtensions && args.extensions.assignmentDate) {
+    message.push(
+      `The new deadline is on ${new Date(
```
Comment (0x4007) [inline src/helpers/remind-and-remove.ts:117]: Can you match the style 

https://github.com/Meniole/daemon-disqualifier/issues/34#issuecomment-2709976511

**Review by 0x4007 — APPROVED** [review]

**Review by whilefoo — APPROVED** [review]

**Comment by gentlementlegen** [comment]
@0x4007 Made requested formatting changes: https://github.com/Meniole/daemon-disqualifier/issues/34#issuecomment-2713548282
